{
  "openapi": "3.0.1",
  "info": {
    "title": "Admin",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [],
  "paths": {
    "/api/admin/permission/list": {
      "get": {
        "summary": "listPermissions",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "name",
            "in": "query",
            "description": "",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "code",
            "in": "query",
            "description": "",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "type",
            "in": "query",
            "description": " MENU :MENU\nBUTTON :BUTTON\nAPI :API\nDATA :DATA\nOTHER :OTHER",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "resource",
            "in": "query",
            "description": "",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "parentId",
            "in": "query",
            "description": "",
            "required": false,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ApiResponsePagePermissionResp"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/api/admin/permission": {
      "post": {
        "summary": "addPermission",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreatePermRequest",
                "description": ""
              },
              "example": "{\r\n    \"name\": \"test perm\",\r\n    \"description\": \"test perm description\",\r\n    \"type\": \"API\",\r\n    \"resource\": \"api/test/\",\r\n}"
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ApiResponseVoid"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/api/admin/permission/{id}": {
      "get": {
        "summary": "getPermission",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ApiResponsePermissionResp"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "put": {
        "summary": "updatePermission",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdatePermRequest",
                "description": ""
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ApiResponseVoid"
                },
                "examples": {
                  "1": {
                    "summary": "成功示例",
                    "value": {
                      "code": "",
                      "message": "",
                      "data": null
                    }
                  },
                  "2": {
                    "summary": "成功示例",
                    "value": {
                      "code": "",
                      "message": "",
                      "data": null
                    }
                  },
                  "3": {
                    "summary": "成功示例",
                    "value": {
                      "code": "",
                      "message": "",
                      "data": null
                    }
                  },
                  "4": {
                    "summary": "成功示例",
                    "value": {
                      "code": "",
                      "message": "",
                      "data": null
                    }
                  },
                  "5": {
                    "summary": "成功示例",
                    "value": {
                      "code": "",
                      "message": "",
                      "data": null
                    }
                  },
                  "6": {
                    "summary": "成功示例",
                    "value": {
                      "code": "",
                      "message": "",
                      "data": null
                    }
                  },
                  "7": {
                    "summary": "成功示例",
                    "value": {
                      "code": "",
                      "message": "",
                      "data": null
                    }
                  },
                  "8": {
                    "summary": "成功示例",
                    "value": {
                      "code": "",
                      "message": "",
                      "data": null
                    }
                  },
                  "9": {
                    "summary": "成功示例",
                    "value": {
                      "code": "",
                      "message": "",
                      "data": null
                    }
                  },
                  "10": {
                    "summary": "成功示例",
                    "value": {
                      "code": "",
                      "message": "",
                      "data": null
                    }
                  },
                  "11": {
                    "summary": "成功示例",
                    "value": {
                      "code": "",
                      "message": "",
                      "data": null
                    }
                  },
                  "12": {
                    "summary": "成功示例",
                    "value": {
                      "code": "",
                      "message": "",
                      "data": null
                    }
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "delete": {
        "summary": "deletePermission",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ApiResponseVoid"
                },
                "examples": {
                  "1": {
                    "summary": "成功示例",
                    "value": {
                      "code": "",
                      "message": "",
                      "data": null
                    }
                  },
                  "2": {
                    "summary": "成功示例",
                    "value": {
                      "code": "",
                      "message": "",
                      "data": null
                    }
                  },
                  "3": {
                    "summary": "成功示例",
                    "value": {
                      "code": "",
                      "message": "",
                      "data": null
                    }
                  },
                  "4": {
                    "summary": "成功示例",
                    "value": {
                      "code": "",
                      "message": "",
                      "data": null
                    }
                  },
                  "5": {
                    "summary": "成功示例",
                    "value": {
                      "code": "",
                      "message": "",
                      "data": null
                    }
                  },
                  "6": {
                    "summary": "成功示例",
                    "value": {
                      "code": "",
                      "message": "",
                      "data": null
                    }
                  },
                  "7": {
                    "summary": "成功示例",
                    "value": {
                      "code": "",
                      "message": "",
                      "data": null
                    }
                  },
                  "8": {
                    "summary": "成功示例",
                    "value": {
                      "code": "",
                      "message": "",
                      "data": null
                    }
                  },
                  "9": {
                    "summary": "成功示例",
                    "value": {
                      "code": "",
                      "message": "",
                      "data": null
                    }
                  },
                  "10": {
                    "summary": "成功示例",
                    "value": {
                      "code": "",
                      "message": "",
                      "data": null
                    }
                  },
                  "11": {
                    "summary": "成功示例",
                    "value": {
                      "code": "",
                      "message": "",
                      "data": null
                    }
                  },
                  "12": {
                    "summary": "成功示例",
                    "value": {
                      "code": "",
                      "message": "",
                      "data": null
                    }
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/api/admin/permission/{id}/users": {
      "get": {
        "summary": "getPermUsers",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ApiResponsePageUserInfoARes"
                },
                "example": {
                  "code": "",
                  "message": "",
                  "data": {
                    "content": [
                      {
                        "uid": 0,
                        "username": "",
                        "accountStatus": "",
                        "statusChangedAt": {
                          "seconds": 0,
                          "nanos": 0,
                          "epochSecond": 0,
                          "nano": 0
                        },
                        "updatedAt": {
                          "seconds": 0,
                          "nanos": 0,
                          "epochSecond": 0,
                          "nano": 0
                        },
                        "createdAt": {
                          "seconds": 0,
                          "nanos": 0,
                          "epochSecond": 0,
                          "nano": 0
                        },
                        "nickname": "",
                        "avatarUrl": "",
                        "lastActiveAt": {
                          "seconds": 0,
                          "nanos": 0,
                          "epochSecond": 0,
                          "nano": 0
                        }
                      }
                    ],
                    "pageable": {
                      "paged": false,
                      "unpaged": false,
                      "pageNumber": 0,
                      "pageSize": 0,
                      "offset": 0,
                      "sort": [
                        {
                          "direction": "",
                          "property": "",
                          "ignoreCase": false,
                          "nullHandling": "",
                          "ascending": false,
                          "descending": false
                        }
                      ]
                    },
                    "total": 0,
                    "empty": false,
                    "number": 0,
                    "size": 0,
                    "numberOfElements": 0,
                    "sort": [
                      {
                        "direction": "",
                        "property": "",
                        "ignoreCase": false,
                        "nullHandling": "",
                        "ascending": false,
                        "descending": false
                      }
                    ],
                    "first": false,
                    "last": false,
                    "totalPages": 0,
                    "totalElements": 0
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "post": {
        "summary": "assignPermToUsers",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/assignPermToUsersReq",
                "description": ""
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ApiResponseBatchResult"
                },
                "example": {
                  "code": "",
                  "message": "",
                  "data": {
                    "requested": 0,
                    "success": 0,
                    "ignored": 0,
                    "failed": 0,
                    "ignoredIds": [
                      0
                    ],
                    "failedIds": [
                      0
                    ],
                    "message": ""
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "put": {
        "summary": "putPermUsers",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/assignPermToUsersReq",
                "description": ""
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ApiResponseBatchResult"
                },
                "example": {
                  "code": "",
                  "message": "",
                  "data": {
                    "requested": 0,
                    "success": 0,
                    "ignored": 0,
                    "failed": 0,
                    "ignoredIds": [
                      0
                    ],
                    "failedIds": [
                      0
                    ],
                    "message": ""
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "delete": {
        "summary": "deletePermUsers",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/removePermUsersReq",
                "description": ""
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ApiResponseBatchResult"
                },
                "example": {
                  "code": "",
                  "message": "",
                  "data": {
                    "requested": 0,
                    "success": 0,
                    "ignored": 0,
                    "failed": 0,
                    "ignoredIds": [
                      0
                    ],
                    "failedIds": [
                      0
                    ],
                    "message": ""
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/api/admin/permission/options": {
      "get": {
        "summary": "getPermOptions",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ApiResponseListOptionVO"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "Instant": {
        "type": "object",
        "properties": {
          "seconds": {
            "type": "integer",
            "description": "The number of seconds from the epoch of 1970-01-01T00:00:00Z.",
            "format": "int64"
          },
          "nanos": {
            "type": "integer",
            "description": "The number of nanoseconds, later along the time-line, from the seconds field.\nThis is always positive, and never exceeds 999,999,999."
          }
        }
      },
      "Sort": {
        "type": "object",
        "properties": {
          "direction": {
            "type": "string",
            "description": "",
            "enum": [
              "ASC",
              "DESC"
            ]
          },
          "property": {
            "type": "string",
            "description": ""
          },
          "ignoreCase": {
            "type": "boolean",
            "description": ""
          },
          "nullHandling": {
            "type": "string",
            "description": "",
            "enum": [
              "NATIVE",
              "NULLS_FIRST",
              "NULLS_LAST"
            ]
          },
          "ascending": {
            "type": "boolean",
            "description": "Returns whether sorting for this property shall be ascending."
          },
          "descending": {
            "type": "boolean",
            "description": "Returns whether sorting for this property shall be descending."
          }
        }
      },
      "Pageable": {
        "type": "object",
        "properties": {
          "paged": {
            "type": "boolean",
            "description": "Returns whether the current{@link Pageable} contains pagination information."
          },
          "unpaged": {
            "type": "boolean",
            "description": "Returns whether the current{@link Pageable} does not contain pagination information."
          },
          "pageNumber": {
            "type": "integer",
            "description": "Returns the page to be returned."
          },
          "pageSize": {
            "type": "integer",
            "description": "Returns the number of items to be returned."
          },
          "offset": {
            "type": "integer",
            "description": "Returns the offset to be taken according to the underlying page and page size.",
            "format": "int64"
          },
          "sort": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Sort",
              "description": "org.springframework.data.domain.Sort"
            },
            "description": "Returns the sorting parameters."
          }
        }
      },
      "ApiResponseVoid": {
        "type": "object",
        "properties": {
          "code": {
            "type": "string",
            "description": ""
          },
          "message": {
            "type": "string",
            "description": ""
          },
          "data": {
            "description": "",
            "type": "null"
          }
        }
      },
      "UserInfoARes": {
        "type": "object",
        "properties": {
          "uid": {
            "type": "integer",
            "description": "",
            "format": "int64"
          },
          "username": {
            "type": "string",
            "description": ""
          },
          "accountStatus": {
            "type": "string",
            "description": "",
            "enum": [
              "ACTIVE",
              "SUSPENDED",
              "DEACTIVATED",
              "DELETED"
            ]
          },
          "statusChangedAt": {
            "$ref": "#/components/schemas/Instant",
            "description": ""
          },
          "updatedAt": {
            "$ref": "#/components/schemas/Instant",
            "description": ""
          },
          "createdAt": {
            "$ref": "#/components/schemas/Instant",
            "description": ""
          },
          "nickname": {
            "type": "string",
            "description": ""
          },
          "avatarUrl": {
            "type": "string",
            "description": ""
          },
          "lastActiveAt": {
            "$ref": "#/components/schemas/Instant",
            "description": ""
          }
        }
      },
      "PageUserInfoARes": {
        "type": "object",
        "properties": {
          "content": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/UserInfoARes",
              "description": "DTO for{@link User}"
            },
            "description": ""
          },
          "pageable": {
            "$ref": "#/components/schemas/Pageable",
            "description": ""
          },
          "total": {
            "type": "integer",
            "description": "",
            "format": "int64"
          },
          "empty": {
            "type": "boolean",
            "description": "Returns whether the current{@link Streamable} is empty."
          },
          "number": {
            "type": "integer"
          },
          "size": {
            "type": "integer"
          },
          "numberOfElements": {
            "type": "integer"
          },
          "sort": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Sort",
              "description": "org.springframework.data.domain.Sort"
            }
          },
          "first": {
            "type": "boolean"
          },
          "last": {
            "type": "boolean"
          },
          "totalPages": {
            "type": "integer"
          },
          "totalElements": {
            "type": "integer",
            "format": "int64"
          }
        }
      },
      "ApiResponsePageUserInfoARes": {
        "type": "object",
        "properties": {
          "code": {
            "type": "string",
            "description": ""
          },
          "message": {
            "type": "string",
            "description": ""
          },
          "data": {
            "$ref": "#/components/schemas/PageUserInfoARes",
            "description": ""
          }
        }
      },
      "PermissionResp": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "description": ""
          },
          "code": {
            "type": "string",
            "description": ""
          },
          "name": {
            "type": "string",
            "description": ""
          },
          "orderWeight": {
            "type": "integer",
            "description": ""
          },
          "description": {
            "type": "string",
            "description": ""
          },
          "type": {
            "type": "string",
            "description": "",
            "enum": [
              "MENU",
              "BUTTON",
              "API",
              "DATA",
              "OTHER"
            ]
          },
          "resource": {
            "type": "string",
            "description": ""
          },
          "isSystem": {
            "type": "boolean",
            "description": ""
          },
          "parentId": {
            "type": "integer",
            "description": ""
          },
          "createdAt": {
            "$ref": "#/components/schemas/Instant",
            "description": ""
          }
        }
      },
      "PagePermissionResp": {
        "type": "object",
        "properties": {
          "content": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/PermissionResp",
              "description": "DTO for{@link org.waterwood.waterfunservicecore.entity.Permission}"
            },
            "description": ""
          },
          "pageable": {
            "$ref": "#/components/schemas/Pageable",
            "description": ""
          },
          "total": {
            "type": "integer",
            "description": "",
            "format": "int64"
          },
          "empty": {
            "type": "boolean",
            "description": "Returns whether the current{@link Streamable} is empty."
          },
          "number": {
            "type": "integer"
          },
          "size": {
            "type": "integer"
          },
          "numberOfElements": {
            "type": "integer"
          },
          "sort": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Sort",
              "description": "org.springframework.data.domain.Sort"
            }
          },
          "first": {
            "type": "boolean"
          },
          "last": {
            "type": "boolean"
          },
          "totalPages": {
            "type": "integer"
          },
          "totalElements": {
            "type": "integer",
            "format": "int64"
          }
        }
      },
      "ApiResponsePagePermissionResp": {
        "type": "object",
        "properties": {
          "code": {
            "type": "string",
            "description": ""
          },
          "message": {
            "type": "string",
            "description": ""
          },
          "data": {
            "$ref": "#/components/schemas/PagePermissionResp",
            "description": ""
          }
        }
      },
      "ApiResponsePermissionResp": {
        "type": "object",
        "properties": {
          "code": {
            "type": "string",
            "description": ""
          },
          "message": {
            "type": "string",
            "description": ""
          },
          "data": {
            "$ref": "#/components/schemas/PermissionResp",
            "description": ""
          }
        }
      },
      "CreatePermRequest": {
        "type": "object",
        "properties": {
          "code": {
            "type": "string",
            "description": "",
            "maxLength": 50
          },
          "name": {
            "type": "string",
            "description": "",
            "maxLength": 50
          },
          "description": {
            "type": "string",
            "description": "",
            "maxLength": 255
          },
          "type": {
            "type": "string",
            "description": "",
            "enum": [
              "MENU",
              "BUTTON",
              "API",
              "DATA",
              "OTHER"
            ]
          },
          "resource": {
            "type": "string",
            "description": "",
            "maxLength": 255
          },
          "parentId": {
            "type": "integer",
            "description": ""
          },
          "orderWeight": {
            "type": "integer",
            "description": ""
          },
          "isSystem": {
            "type": "boolean",
            "description": ""
          }
        },
        "required": [
          "name",
          "resource"
        ]
      },
      "UpdatePermRequest": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "description": ""
          },
          "code": {
            "type": "string",
            "description": ""
          },
          "name": {
            "type": "string",
            "description": ""
          },
          "orderWeight": {
            "type": "integer",
            "description": ""
          },
          "description": {
            "type": "string",
            "description": ""
          },
          "type": {
            "type": "string",
            "description": "",
            "enum": [
              "MENU",
              "BUTTON",
              "API",
              "DATA",
              "OTHER"
            ]
          },
          "resource": {
            "type": "string",
            "description": ""
          },
          "parentId": {
            "type": "integer",
            "description": ""
          },
          "isSystem": {
            "type": "boolean",
            "description": ""
          }
        },
        "required": [
          "id"
        ]
      },
      "BatchResult": {
        "type": "object",
        "properties": {
          "requested": {
            "type": "integer",
            "description": ""
          },
          "success": {
            "type": "integer",
            "description": ""
          },
          "ignored": {
            "type": "integer",
            "description": ""
          },
          "failed": {
            "type": "integer",
            "description": ""
          },
          "ignoredIds": {
            "type": "array",
            "items": {
              "type": "integer"
            },
            "description": ""
          },
          "failedIds": {
            "type": "array",
            "items": {
              "type": "integer"
            },
            "description": ""
          },
          "message": {
            "type": "string",
            "description": ""
          }
        }
      },
      "ApiResponseBatchResult": {
        "type": "object",
        "properties": {
          "code": {
            "type": "string",
            "description": ""
          },
          "message": {
            "type": "string",
            "description": ""
          },
          "data": {
            "$ref": "#/components/schemas/BatchResult",
            "description": ""
          }
        }
      },
      "assignPermToUsersReq": {
        "type": "object",
        "properties": {
          "ids": {
            "type": "array",
            "items": {
              "type": "integer"
            },
            "description": ""
          },
          "expiresAt": {
            "$ref": "#/components/schemas/Instant",
            "description": ""
          }
        }
      },
      "removePermUsersReq": {
        "type": "object",
        "properties": {
          "userUids": {
            "type": "array",
            "items": {
              "type": "integer"
            },
            "description": ""
          }
        }
      },
      "OptionVO": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "description": "",
            "format": "int64"
          },
          "code": {
            "type": "string",
            "description": ""
          },
          "name": {
            "type": "string",
            "description": ""
          },
          "disabled": {
            "type": "boolean",
            "description": "",
            "default": false
          }
        }
      },
      "ApiResponseListOptionVO": {
        "type": "object",
        "properties": {
          "code": {
            "type": "string",
            "description": ""
          },
          "message": {
            "type": "string",
            "description": ""
          },
          "data": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/OptionVO",
              "description": "org.waterwood.api.VO.OptionVO"
            },
            "description": ""
          }
        }
      }
    },
    "responses": {},
    "securitySchemes": {
      "bearer": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "servers": [],
  "security": []
}